### PR TITLE
Added alias option and fixed some issues

### PR DESCRIPTION
**Pull request by unimonkiez**
* Import to absolute paths fixed.
* Import to files without extension but has a `.` in file name fixed (for example `bla.bloop` should import `bla.bloop.ext` instead of `bla.ext`).
* Added `alias` property, when your build process has alias', then you can set alias too (added example in `README.md`).   

Tests been failing even before I started so I didn't bother.
Waiting for it to be on npm and thanks in advance!

### CODE REVIEW

**Comment by bignimbus** [comment]
@unimonkiez thanks so much for the pull request.  I'm not sure why your tests are failing locally on the master branch; It Works On My Machine™.  Maybe it's high time I used a CI service.  I'll review these changes and write some unit tests in the near future.  Thanks again!

**Comment by unimonkiez** [comment]
@bignimbus Hey, found the issue, I'm using windows for development and it adds a hidden `%0D` character to the outputs, so I just removed it (I think it got something to do with CRLF).

Also added unit test for my new features.  :+1: 
Ready to pull?

**Comment by bignimbus** [comment]
@unimonkiez thanks very much for the update.  I am getting a failure when I run the tests locally.

screen shot 2016-08-23 at 10 13 04 pm

Additionally, I wouldn't feel right about merging this in until we broke the additions to the `read` function into several smaller, single-purpose functions.  For example, the `_` feature could be put into its own function and unit tested on its own.  Same with the `alias` feature.  I could take over from here if you'd like, I know you've put a lot of effort in and I don't want to use more of your time than you're willing to give.

I do appreciate your contribution and hope to get this merged in soon.

**Comment by unimonkiez** [comment]
Cool! will be waiting :smile:

**Comment by bignimbus** [comment]
@unimonkiez Thanks for your patience.  I'll be releasing several patches in succession on the `0.2.x` minor version.  `0.2.7` was just released.  It includes fixes for `_` filenames and absolute file paths in unix filesystems.  `0.2.8` will add compatibility with windows filesystems by favoring `path` methods over hardcoded `/`s.  The alias functionality will be released with version `0.3.0`.

**Comment by unimonkiez** [comment]
Thanks! looks promising.
When will 0.3.0 will be released?

**Comment by bignimbus** [comment]
Not sure, probably within 1-2 weeks

**Comment by bignimbus** [comment]
@unimonkiez 0.3.0 release candidate is in `master` branch.  Please pull and let me know if there are any unexpected results.  I plan to publish in npm soon, but wanted to get your take on it since you requested the feature.  Thanks so much for your input and patience.

**Comment by unimonkiez** [comment]
But not yet in `npm` so I can't try it yet :smile:

**Comment by unimonkiez** [comment]
@bignimbus 
Hey, I get errors of file which I imported without an extension but has a dot in the name is not found because part of the file name is being trimmed.
I fixed it in [this](https://github.com/bignimbus/import-resolve/pull/4/files#diff-168726dbe96b3ce427e7fedce31bb0bcR48) code

**Comment by unimonkiez** [comment]
Added the condition to the `trimExtension` and everything works including `aliases`
```javascript
ImportResolver.prototype.trimExtension = function (filename) {
    var prefix = filename.match(/^\.*/);
    prefix = prefix && prefix.length ? prefix[0] : '';

    // Some files doesn't have an extension, in that case we shouldn't trim  
    // the last characters after the dot because it is a part of the file's name
    if (filename.indexOf(this.ext) !== -1) {
        filename = filename.slice(prefix.length).split('.');
        filename = filename.length > 1 ? filename.slice(0, -1).join('.') : filename[0];
    }
    return prefix + filename;
};
```

**Comment by bignimbus** [comment]
@unimonkiez updated.

**Comment by unimonkiez** [comment]
@bignimbus Cool! waiting for `0.3.0` on `npm`

**Comment by bignimbus** [comment]
[0.3.0](https://www.npmjs.com/package/import-resolve) published.

**Comment by unimonkiez** [comment]
Thanks! already in my project, works :+1:

**Pull request closed without merging**
